import { Category } from '@/types/products';

// export const CATEGORIES: Category[] = [
//   {
//     id: 'bafles-category',
//     name: 'Bafles',
//     slug: 'bafles',
//     description: 'Bocinas activas, pasivas y más.',
//     color: 'text-cyan-600',
//     image: '/images/bafles.webp',
//     alt: 'Categoría Bafles',
//   },
//   {
//     id: 'humo-category',
//     name: 'Maquinaria de Humo',
//     slug: 'maquinaria-de-humo',
//     description: 'Efectos visuales para ambientar.',
//     color: 'text-indigo-600',
//     image: '/images/humo.webp',
//     alt: 'Máquina de humo en acción',
//   },
//   {
//     id: 'luces-category',
//     name: 'Luces',
//     slug: 'luces',
//     description: 'Luces LED, scanners y cabezas móviles.',
//     color: 'text-rose-600',
//     image: '/images/luces.webp',
//     alt: 'Luces profesionales para eventos',
//   },
//   {
//     id: 'iluminacion-category',
//     name: 'Iluminación',
//     slug: 'iluminacion',
//     description: 'Paneles, par LED, y sistemas de control.',
//     color: 'text-yellow-600',
//     image: '/images/iluminacion.webp',
//     alt: 'Iluminación de escenario',
//   },
//   {
//     id: 'estructuras-category',
//     name: 'Estructuras',
//     slug: 'estructuras',
//     description: 'Trusses, escenarios, soportes profesionales.',
//     color: 'text-lime-600',
//     image: '/images/estructuras.webp',
//     alt: 'Estructuras para conciertos',
//   },
//   {
//     id: 'accesorios-category',
//     name: 'Accesorios',
//     slug: 'accesorios',
//     description: 'Cables, conectores, soportes y más.',
//     color: 'text-emerald-600',
//     image: '/images/accesorios.webp',
//     alt: 'Accesorios de audio e iluminación',
//   },
//   {
//     id: 'pantallas-category',
//     name: 'Pantallas',
//     slug: 'pantallas',
//     description: 'Pantallas LED para eventos y publicidad visual.',
//     color: 'text-blue-600',
//     image: '/images/pantallas.webp',
//     alt: 'Pantalla LED en escenario de concierto',
//   },
// ];

export const CATEGORIES: Category[] = [
  {
    id: 'bafles-category',
    name: 'Bafles',
    slug: 'bafles',
    shortDesc: 'Bocinas activas, pasivas y más.',
    description: 'Bocinas activas, pasivas y más.',
    color: 'text-cyan-600',
    image: '/images/bafles.webp',
    alt: 'Categoría Bafles',
  },
  {
    id: 'arreglos-lineales-category',
    name: 'Arreglos lineales',
    slug: 'arreglos-lineales',
    description:
      'Experimenta un sonido potente y direccional con nuestros arreglos lineales profesionales. Ideales para conciertos, eventos y espacios amplios que exigen cobertura y claridad sonora de alto nivel.',
    shortDesc: 'Cobertura precisa y sonido potente.',
    color: 'text-cyan-600',
    image: '/images/arreglos-lineales.webp',
    alt: 'Categoría Arreglos lineales',
  },
  {
    id: 'sistemas-de-audio-category',
    name: 'Sistemas de audio',
    slug: 'sistemas-de-audio',
    description:
      'Soluciones de audio completas para todo tipo de evento. Nuestros sistemas activos y pasivos ofrecen calidad, conectividad y potencia en un solo paquete, listos para usarse en cualquier ocasión.',
    shortDesc: 'Equipos completos listos para usarse.',
    color: 'text-blue-600',
    image: '/images/sistema-de-audio.webp',
    alt: 'Categoría Sistemas de audio',
  },
  {
    id: 'subwoofers-category',
    name: 'Subwoofers',
    slug: 'subwoofers',
    description:
      'Haz que tu evento retumbe con graves profundos y potentes. Nuestros subwoofers están diseñados para ofrecer una experiencia sonora inmersiva, ideal para música en vivo, DJ sets y presentaciones profesionales.',
    shortDesc: 'Graves profundos y contundentes.',
    color: 'text-yellow-600',
    image: '/images/subwoofers.webp',
    alt: 'Categoría Subwoofers',
  },
  {
    id: 'microfonos-category',
    name: 'Micrófonos',
    slug: 'microfonos',
    description: 'Micrófonos con cable listos para escenario.',
    shortDesc: 'Graves profundos y contundentes.',
    color: 'text-indigo-600',
    image: '/images/microfonos-cable.webp',
    alt: 'Categoría Micrófonos',
  },
  {
    id: 'microfonos-inalambricos-category',
    name: 'Micrófonos inalámbricos',
    slug: 'microfonos-inalambricos',
    description:
      'Libertad de movimiento con calidad profesional. Nuestros micrófonos inalámbricos ofrecen excelente alcance, nitidez y estabilidad, ideales para presentaciones, espectáculos y eventos en vivo. ',
    shortDesc: 'Libertad total con excelente calidad de voz.',
    color: 'text-emerald-600',
    image: '/images/microfonos-inalambricos.webp',
    alt: 'Categoría Micrófonos inalámbricos',
  },
  {
    id: 'mezcladoras-category',
    name: 'Mezcladoras',
    slug: 'mezcladoras',
    description:
      'Control total de tu sonido. Nuestras mezcladoras te permiten ecualizar, mezclar y dar forma a cada canal con precisión, perfectas para DJs, músicos y técnicos de audio.',
    shortDesc: 'Control y mezcla profesional en tus manos.',
    color: 'text-blue-600',
    image: '/images/mezcladoras.webp',
    alt: 'Categoría Mezcladoras',
  },
  {
    id: 'accesorios-category',
    name: 'Accesorios',
    slug: 'accesorios',
    description:
      'Todo lo que necesitas para complementar tu equipo. Soportes, adaptadores, racks y más para facilitar la instalación y optimizar el rendimiento de tu sistema de audio e iluminación.',
    shortDesc: 'Complementa y optimiza tu equipo.',
    color: 'text-rose-600',
    image: '/images/accesorios.webp',
    alt: 'Categoría Accesorios',
  },
  {
    id: 'cables-category',
    name: 'Cables',
    slug: 'cables',
    description:
      'Conexiones seguras y de calidad profesional. Contamos con cables para audio, micrófono y alimentación en diferentes longitudes, diseñados para garantizar transmisión estable y durabilidad.',
    shortDesc: 'Conexiones confiables para tu sistema.',
    color: 'text-lime-600',
    image: '/images/cables.webp',
    alt: 'Categoría Cables',
  },
  {
    id: 'humo-category',
    name: 'Maquinaria de Humo',
    slug: 'maquinaria-de-humo',
    description:
      'En esta categoría encontrarás equipos ideales para ambientar conciertos, escenarios, fiestas, clubes o presentaciones. Las máquinas de humo realzan la iluminación y los efectos visuales, generando un entorno envolvente y dinámico que cautiva al público. Disponibles en distintos tamaños y potencias, nuestras opciones se adaptan tanto a instalaciones móviles como a montajes fijos. Compatibles con control DMX y diseñadas para un rendimiento confiable y continuo.',
    shortDesc: 'Efectos visuales para ambientar.',
    color: 'text-indigo-600',
    image: '/images/humo.webp',
    alt: 'Máquina de humo en acción',
  },
  {
    id: 'iluminacion-category',
    name: 'Iluminación',
    slug: 'iluminacion',
    description:
      'Descubre nuestra línea de soluciones de iluminación escénica, que incluye paneles LED, par lights, barras, efectos inteligentes y sistemas de control DMX. Cada producto está diseñado para ofrecer potencia, color, precisión y confiabilidad, ideales para conciertos, teatros, eventos sociales, clubs, templos, y producciones audiovisuales.',
    shortDesc: 'Paneles, par LED, y sistemas de control.',
    color: 'text-yellow-600',
    image: '/images/iluminacion.webp',
    alt: 'Iluminación de escenario',
  },
  {
    id: 'luces-category',
    name: 'Luces',
    slug: 'luces',
    description:
      'Explora nuestra gama de luces LED, scanners y cabezas móviles diseñadas para elevar cualquier presentación visual. Ya sea que trabajes en eventos sociales, conciertos, iglesias o clubs nocturnos, nuestras luminarias ofrecen potencia, versatilidad y precisión.',
    shortDesc: 'Luces LED, scanners y cabezas móviles.',
    color: 'text-rose-600',
    image: '/images/luces.webp',
    alt: 'Luces profesionales para eventos',
  },
  {
    id: 'procesadores-audio-category',
    name: 'Procesadores de audio',
    slug: 'procesadores-audio',
    description:
      'Optimiza el sonido de tus eventos con nuestra selección de procesadores de audio profesionales. Desde crossovers digitales hasta DSPs avanzados, encuentra la herramienta ideal para lograr una mezcla limpia, precisa y bien definida en cualquier entorno.',
    shortDesc: 'DSPs, crossovers y más.',
    color: 'text-sky-600',
    image: '/images/procesadores-de-audio.webp',
    alt: 'Procesadores de audio profesionales',
  },
];
