import { Category } from '@/types/products';

export const CATEGORIES: Category[] = [
  {
    id: 'bafles-category',
    name: 'Bafles',
    slug: 'bafles',
    description: 'Bocinas activas, pasivas y más.',
    color: 'text-cyan-600',
    image: '/images/bafles.webp',
    alt: 'Categoría Bafles',
  },
  {
    id: 'humo-category',
    name: 'Maquinaria de Humo',
    slug: 'maquinaria-de-humo',
    description: 'Efectos visuales para ambientar.',
    color: 'text-indigo-600',
    image: '/images/humo.webp',
    alt: 'Máquina de humo en acción',
  },
  {
    id: 'luces-category',
    name: 'Luces',
    slug: 'luces',
    description: 'Luces LED, scanners y cabezas móviles.',
    color: 'text-rose-600',
    image: '/images/luces.webp',
    alt: 'Luces profesionales para eventos',
  },
  {
    id: 'iluminacion-category',
    name: 'Iluminación',
    slug: 'iluminacion',
    description: 'Paneles, par LED, y sistemas de control.',
    color: 'text-yellow-600',
    image: '/images/iluminacion.webp',
    alt: 'Iluminación de escenario',
  },
  {
    id: 'estructuras-category',
    name: 'Estructuras',
    slug: 'estructuras',
    description: 'Trusses, escenarios, soportes profesionales.',
    color: 'text-lime-600',
    image: '/images/estructuras.webp',
    alt: 'Estructuras para conciertos',
  },
  {
    id: 'accesorios-category',
    name: 'Accesorios',
    slug: 'accesorios',
    description: 'Cables, conectores, soportes y más.',
    color: 'text-emerald-600',
    image: '/images/accesorios.webp',
    alt: 'Accesorios de audio e iluminación',
  },
  {
    id: 'pantallas-category',
    name: 'Pantallas',
    slug: 'pantallas',
    description: 'Pantallas LED para eventos y publicidad visual.',
    color: 'text-blue-600',
    image: '/images/pantallas.webp',
    alt: 'Pantalla LED en escenario de concierto',
  },
];
