import { Product } from '@/types/products';

export const PRODUCTS: Product[] = [
  {
    id: '001',
    name: 'Bafles Producto 1',
    slug: 'bafles-producto-1',
    description: 'Descripción del producto 1 de la categoría Bafles.',
    price: 1500,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'bafles-category',
    features: ['Característica 1', 'Característica 2', 'Característica 3'],
    videoUrl: 'https://www.youtube.com/watch?v=VGL3x3Cc1io',
  },
  {
    id: '002',
    name: 'Bafles Producto 2',
    slug: 'bafles-producto-2',
    description: 'Descripción del producto 2 de la categoría Bafles.',
    price: 2000,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'bafles-category',
    features: ['Característica 1', 'Característica 2', 'Característica 3'],
    videoUrl: 'https://www.youtube.com/watch?v=VGL3x3Cc1io',
  },
  {
    id: '003',
    name: 'Bafles Producto 3',
    slug: 'bafles-producto-3',
    description: 'Descripción del producto 3 de la categoría Bafles.',
    price: 2500,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'bafles-category',
    features: ['Característica 1', 'Característica 2', 'Característica 3'],
    videoUrl: 'https://www.youtube.com/watch?v=VGL3x3Cc1io',
  },
  {
    id: '004',
    name: 'Bafles Producto 4',
    slug: 'bafles-producto-4',
    description: 'Descripción del producto 4 de la categoría Bafles.',
    price: 3000,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'bafles-category',
    features: ['Característica 1', 'Característica 2', 'Característica 3'],
    videoUrl: 'https://www.youtube.com/watch?v=VGL3x3Cc1io',
  },
  {
    id: '005',
    name: 'Bafles Producto 5',
    slug: 'bafles-producto-5',
    description: 'Descripción del producto 5 de la categoría Bafles.',
    price: 3500,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'bafles-category',
    features: ['Característica 1', 'Característica 2', 'Característica 3'],
    videoUrl: 'https://www.youtube.com/watch?v=VGL3x3Cc1io',
  },
  {
    id: '006',
    name: 'Maquinaria de Humo Producto 1',
    slug: 'maquinaria-de-humo-producto-1',
    description:
      'Descripción del producto 1 de la categoría Maquinaria de Humo.',
    price: 1500,
    coverImage: '/images/humo.webp',
    images: ['/images/humo.webp'],
    categoryId: 'humo-category',
    features: ['Característica 1', 'Característica 2', 'Característica 3'],
    videoUrl: 'https://www.youtube.com/watch?v=VGL3x3Cc1io',
  },
  {
    id: '007',
    name: 'Maquinaria de Humo Producto 2',
    slug: 'maquinaria-de-humo-producto-2',
    description:
      'Descripción del producto 2 de la categoría Maquinaria de Humo.',
    price: 2000,
    coverImage: '/images/humo.webp',
    images: ['/images/humo.webp'],
    categoryId: 'humo-category',
    features: ['Característica 1', 'Característica 2', 'Característica 3'],
    videoUrl: 'https://www.youtube.com/watch?v=VGL3x3Cc1io',
  },
  {
    id: '008',
    name: 'Maquinaria de Humo Producto 3',
    slug: 'maquinaria-de-humo-producto-3',
    description:
      'Descripción del producto 3 de la categoría Maquinaria de Humo.',
    price: 2500,
    coverImage: '/images/humo.webp',
    images: ['/images/humo.webp'],
    categoryId: 'humo-category',
    features: ['Característica 1', 'Característica 2', 'Característica 3'],
    videoUrl: 'https://www.youtube.com/watch?v=VGL3x3Cc1io',
  },
  {
    id: '009',
    name: 'Maquinaria de Humo Producto 4',
    slug: 'maquinaria-de-humo-producto-4',
    description:
      'Descripción del producto 4 de la categoría Maquinaria de Humo.',
    price: 3000,
    coverImage: '/images/humo.webp',
    images: ['/images/humo.webp'],
    categoryId: 'humo-category',
    features: ['Característica 1', 'Característica 2', 'Característica 3'],
    videoUrl: 'https://www.youtube.com/watch?v=VGL3x3Cc1io',
  },
  {
    id: '010',
    name: 'Maquinaria de Humo Producto 5',
    slug: 'maquinaria-de-humo-producto-5',
    description:
      'Descripción del producto 5 de la categoría Maquinaria de Humo.',
    price: 3500,
    coverImage: '/images/humo.webp',
    images: ['/images/humo.webp'],
    categoryId: 'humo-category',
    features: ['Característica 1', 'Característica 2', 'Característica 3'],
    videoUrl: 'https://www.youtube.com/watch?v=VGL3x3Cc1io',
  },
  {
    id: '011',
    name: 'Luces Producto 1',
    slug: 'luces-producto-1',
    description: 'Descripción del producto 1 de la categoría Luces.',
    price: 1500,
    coverImage: '/images/luces.webp',
    images: ['/images/luces.webp'],
    categoryId: 'luces-category',
    features: ['Característica 1', 'Característica 2', 'Característica 3'],
    videoUrl: 'https://www.youtube.com/watch?v=VGL3x3Cc1io',
  },
  {
    id: '012',
    name: 'Luces Producto 2',
    slug: 'luces-producto-2',
    description: 'Descripción del producto 2 de la categoría Luces.',
    price: 2000,
    coverImage: '/images/luces.webp',
    images: ['/images/luces.webp'],
    categoryId: 'luces-category',
    features: ['Característica 1', 'Característica 2', 'Característica 3'],
    videoUrl: 'https://www.youtube.com/watch?v=VGL3x3Cc1io',
  },
  {
    id: '013',
    name: 'Luces Producto 3',
    slug: 'luces-producto-3',
    description: 'Descripción del producto 3 de la categoría Luces.',
    price: 2500,
    coverImage: '/images/luces.webp',
    images: ['/images/luces.webp'],
    categoryId: 'luces-category',
    features: ['Característica 1', 'Característica 2', 'Característica 3'],
    videoUrl: 'https://www.youtube.com/watch?v=VGL3x3Cc1io',
  },
  {
    id: '014',
    name: 'Luces Producto 4',
    slug: 'luces-producto-4',
    description: 'Descripción del producto 4 de la categoría Luces.',
    price: 3000,
    coverImage: '/images/luces.webp',
    images: ['/images/luces.webp'],
    categoryId: 'luces-category',
    features: ['Característica 1', 'Característica 2', 'Característica 3'],
    videoUrl: 'https://www.youtube.com/watch?v=VGL3x3Cc1io',
  },
  {
    id: '015',
    name: 'Luces Producto 5',
    slug: 'luces-producto-5',
    description: 'Descripción del producto 5 de la categoría Luces.',
    price: 3500,
    coverImage: '/images/luces.webp',
    images: ['/images/luces.webp'],
    categoryId: 'luces-category',
    features: ['Característica 1', 'Característica 2', 'Característica 3'],
    videoUrl: 'https://www.youtube.com/watch?v=VGL3x3Cc1io',
  },
  {
    id: '016',
    name: 'Iluminación Producto 1',
    slug: 'iluminacion-producto-1',
    description: 'Descripción del producto 1 de la categoría Iluminación.',
    price: 1500,
    coverImage: '/images/iluminacion.webp',
    images: ['/images/iluminacion.webp'],
    categoryId: 'iluminacion-category',
    features: ['Característica 1', 'Característica 2', 'Característica 3'],
    videoUrl: 'https://www.youtube.com/watch?v=VGL3x3Cc1io',
  },
  {
    id: '017',
    name: 'Iluminación Producto 2',
    slug: 'iluminacion-producto-2',
    description: 'Descripción del producto 2 de la categoría Iluminación.',
    price: 2000,
    coverImage: '/images/iluminacion.webp',
    images: ['/images/iluminacion.webp'],
    categoryId: 'iluminacion-category',
    features: ['Característica 1', 'Característica 2', 'Característica 3'],
    videoUrl: 'https://www.youtube.com/watch?v=VGL3x3Cc1io',
  },
  {
    id: '018',
    name: 'Iluminación Producto 3',
    slug: 'iluminacion-producto-3',
    description: 'Descripción del producto 3 de la categoría Iluminación.',
    price: 2500,
    coverImage: '/images/iluminacion.webp',
    images: ['/images/iluminacion.webp'],
    categoryId: 'iluminacion-category',
    features: ['Característica 1', 'Característica 2', 'Característica 3'],
    videoUrl: 'https://www.youtube.com/watch?v=VGL3x3Cc1io',
  },
  {
    id: '019',
    name: 'Iluminación Producto 4',
    slug: 'iluminacion-producto-4',
    description: 'Descripción del producto 4 de la categoría Iluminación.',
    price: 3000,
    coverImage: '/images/iluminacion.webp',
    images: ['/images/iluminacion.webp'],
    categoryId: 'iluminacion-category',
    features: ['Característica 1', 'Característica 2', 'Característica 3'],
    videoUrl: 'https://www.youtube.com/watch?v=VGL3x3Cc1io',
  },
  {
    id: '020',
    name: 'Iluminación Producto 5',
    slug: 'iluminacion-producto-5',
    description: 'Descripción del producto 5 de la categoría Iluminación.',
    price: 3500,
    coverImage: '/images/iluminacion.webp',
    images: ['/images/iluminacion.webp'],
    categoryId: 'iluminacion-category',
    features: ['Característica 1', 'Característica 2', 'Característica 3'],
    videoUrl: 'https://www.youtube.com/watch?v=VGL3x3Cc1io',
  },
  {
    id: '021',
    name: 'Estructuras Producto 1',
    slug: 'estructuras-producto-1',
    description: 'Descripción del producto 1 de la categoría Estructuras.',
    price: 1500,
    coverImage: '/images/estructuras.webp',
    images: ['/images/estructuras.webp'],
    categoryId: 'estructuras-category',
    features: ['Característica 1', 'Característica 2', 'Característica 3'],
    videoUrl: 'https://www.youtube.com/watch?v=VGL3x3Cc1io',
  },
  {
    id: '022',
    name: 'Estructuras Producto 2',
    slug: 'estructuras-producto-2',
    description: 'Descripción del producto 2 de la categoría Estructuras.',
    price: 2000,
    coverImage: '/images/estructuras.webp',
    images: ['/images/estructuras.webp'],
    categoryId: 'estructuras-category',
    features: ['Característica 1', 'Característica 2', 'Característica 3'],
    videoUrl: 'https://www.youtube.com/watch?v=VGL3x3Cc1io',
  },
  {
    id: '023',
    name: 'Estructuras Producto 3',
    slug: 'estructuras-producto-3',
    description: 'Descripción del producto 3 de la categoría Estructuras.',
    price: 2500,
    coverImage: '/images/estructuras.webp',
    images: ['/images/estructuras.webp'],
    categoryId: 'estructuras-category',
    features: ['Característica 1', 'Característica 2', 'Característica 3'],
    videoUrl: 'https://www.youtube.com/watch?v=VGL3x3Cc1io',
  },
  {
    id: '024',
    name: 'Estructuras Producto 4',
    slug: 'estructuras-producto-4',
    description: 'Descripción del producto 4 de la categoría Estructuras.',
    price: 3000,
    coverImage: '/images/estructuras.webp',
    images: ['/images/estructuras.webp'],
    categoryId: 'estructuras-category',
    features: ['Característica 1', 'Característica 2', 'Característica 3'],
    videoUrl: 'https://www.youtube.com/watch?v=VGL3x3Cc1io',
  },
  {
    id: '025',
    name: 'Estructuras Producto 5',
    slug: 'estructuras-producto-5',
    description: 'Descripción del producto 5 de la categoría Estructuras.',
    price: 3500,
    coverImage: '/images/estructuras.webp',
    images: ['/images/estructuras.webp'],
    categoryId: 'estructuras-category',
    features: ['Característica 1', 'Característica 2', 'Característica 3'],
    videoUrl: 'https://www.youtube.com/watch?v=VGL3x3Cc1io',
  },
  {
    id: '026',
    name: 'Accesorios Producto 1',
    slug: 'accesorios-producto-1',
    description: 'Descripción del producto 1 de la categoría Accesorios.',
    price: 1500,
    coverImage: '/images/accesorios.webp',
    images: ['/images/accesorios.webp'],
    categoryId: 'accesorios-category',
    features: ['Característica 1', 'Característica 2', 'Característica 3'],
    videoUrl: 'https://www.youtube.com/watch?v=VGL3x3Cc1io',
  },
  {
    id: '027',
    name: 'Accesorios Producto 2',
    slug: 'accesorios-producto-2',
    description: 'Descripción del producto 2 de la categoría Accesorios.',
    price: 2000,
    coverImage: '/images/accesorios.webp',
    images: ['/images/accesorios.webp'],
    categoryId: 'accesorios-category',
    features: ['Característica 1', 'Característica 2', 'Característica 3'],
    videoUrl: 'https://www.youtube.com/watch?v=VGL3x3Cc1io',
  },
  {
    id: '028',
    name: 'Accesorios Producto 3',
    slug: 'accesorios-producto-3',
    description: 'Descripción del producto 3 de la categoría Accesorios.',
    price: 2500,
    coverImage: '/images/accesorios.webp',
    images: ['/images/accesorios.webp'],
    categoryId: 'accesorios-category',
    features: ['Característica 1', 'Característica 2', 'Característica 3'],
    videoUrl: 'https://www.youtube.com/watch?v=VGL3x3Cc1io',
  },
  {
    id: '029',
    name: 'Accesorios Producto 4',
    slug: 'accesorios-producto-4',
    description: 'Descripción del producto 4 de la categoría Accesorios.',
    price: 3000,
    coverImage: '/images/accesorios.webp',
    images: ['/images/accesorios.webp'],
    categoryId: 'accesorios-category',
    features: ['Característica 1', 'Característica 2', 'Característica 3'],
    videoUrl: 'https://www.youtube.com/watch?v=VGL3x3Cc1io',
  },
  {
    id: '030',
    name: 'Accesorios Producto 5',
    slug: 'accesorios-producto-5',
    description: 'Descripción del producto 5 de la categoría Accesorios.',
    price: 3500,
    coverImage: '/images/accesorios.webp',
    images: ['/images/accesorios.webp'],
    categoryId: 'accesorios-category',
    features: ['Característica 1', 'Característica 2', 'Característica 3'],
    videoUrl: 'https://www.youtube.com/watch?v=VGL3x3Cc1io',
  },
  {
    id: '031',
    name: 'Pantallas Producto 1',
    slug: 'pantallas-producto-1',
    description: 'Descripción del producto 1 de la categoría Pantallas.',
    price: 1500,
    coverImage: '/images/pantallas.webp',
    images: ['/images/pantallas.webp'],
    categoryId: 'pantallas-category',
    features: ['Característica 1', 'Característica 2', 'Característica 3'],
    videoUrl: 'https://www.youtube.com/watch?v=VGL3x3Cc1io',
  },
  {
    id: '032',
    name: 'Pantallas Producto 2',
    slug: 'pantallas-producto-2',
    description: 'Descripción del producto 2 de la categoría Pantallas.',
    price: 2000,
    coverImage: '/images/pantallas.webp',
    images: ['/images/pantallas.webp'],
    categoryId: 'pantallas-category',
    features: ['Característica 1', 'Característica 2', 'Característica 3'],
    videoUrl: 'https://www.youtube.com/watch?v=VGL3x3Cc1io',
  },
  {
    id: '033',
    name: 'Pantallas Producto 3',
    slug: 'pantallas-producto-3',
    description: 'Descripción del producto 3 de la categoría Pantallas.',
    price: 2500,
    coverImage: '/images/pantallas.webp',
    images: ['/images/pantallas.webp'],
    categoryId: 'pantallas-category',
    features: ['Característica 1', 'Característica 2', 'Característica 3'],
    videoUrl: 'https://www.youtube.com/watch?v=VGL3x3Cc1io',
  },
  {
    id: '034',
    name: 'Pantallas Producto 4',
    slug: 'pantallas-producto-4',
    description: 'Descripción del producto 4 de la categoría Pantallas.',
    price: 3000,
    coverImage: '/images/pantallas.webp',
    images: ['/images/pantallas.webp'],
    categoryId: 'pantallas-category',
    features: ['Característica 1', 'Característica 2', 'Característica 3'],
    videoUrl: 'https://www.youtube.com/watch?v=VGL3x3Cc1io',
  },
  {
    id: '035',
    name: 'Pantallas Producto 5',
    slug: 'pantallas-producto-5',
    description: 'Descripción del producto 5 de la categoría Pantallas.',
    price: 3500,
    coverImage: '/images/pantallas.webp',
    images: ['/images/pantallas.webp'],
    categoryId: 'pantallas-category',
    features: ['Característica 1', 'Característica 2', 'Característica 3'],
    videoUrl: 'https://www.youtube.com/watch?v=VGL3x3Cc1io',
  },
];

export const getProductsByCategory = (categoryId: string) => {
  return PRODUCTS.filter((product) => product.categoryId === categoryId);
};

export function getProductById(id: string) {
  return PRODUCTS.find((product) => product.id === id);
}
