import { Product } from '@/types/products';

export const PRODUCTS: Product[] = [
  {
    id: '000',
    name: 'MERCURY 12',
    slug: 'bafles-mercury-12',
    description: 'Bafle amplificado de 12" con USB, SD, Bluetooth',
    price: 3763.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'bafles-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '001',
    name: 'MERCURY 15',
    slug: 'bafles-mercury-15',
    description: 'Bafle amplificado de 15" con USB, SD, Bluetooth',
    price: 4716.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'bafles-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '002',
    name: 'TECHNO 315',
    slug: 'bafles-techno-315',
    description: 'Bafle amplificado 15" con DSP, Bluetooth, HPF, plastificado',
    price: 4784.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'bafles-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '003',
    name: 'MERCURY DSP 1201',
    slug: 'bafles-mercury-dsp-1201',
    description: 'Bafle amplificado 12" con DSP, USB, SD, Bluetooth',
    price: 5960.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'bafles-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '004',
    name: 'MERCURY DSP 1501',
    slug: 'bafles-mercury-dsp-1501',
    description: 'Bafle amplificado 15" con DSP, USB, SD, Bluetooth',
    price: 6596.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'bafles-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '005',
    name: 'DIGIPRO 12',
    slug: 'bafles-digipro-12',
    description: 'Bafle amplificado de 12" con DSP 400W RMS',
    price: 5323.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'bafles-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '006',
    name: 'DIGIPRO 15',
    slug: 'bafles-digipro-15',
    description: 'Bafle amplificado de 15" con DSP 500W RMS',
    price: 7322.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'bafles-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '007',
    name: 'NOVA 12',
    slug: 'bafles-nova-12',
    description: 'Bafle amplificado 12" con DSP, 400W RMS, MDF',
    price: 6995.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'bafles-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '008',
    name: 'NOVA 15',
    slug: 'bafles-nova-15',
    description: 'Bafle amplificado 15" con DSP, 450W RMS, MDF',
    price: 8527.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'bafles-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '009',
    name: 'NOVA 215',
    slug: 'bafles-nova-215',
    description: 'Bafle amplificado 2x15" con DSP, 800W RMS, MDF',
    price: 11083.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'bafles-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '016',
    name: 'VXT 208',
    slug: 'arreglos-lineales-vxt-208',
    description: 'Arreglo lineal 2x8", 1 Driver 3", 500W RMS',
    price: 16331.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'arreglos-lineales-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '017',
    name: 'VXT 210',
    slug: 'arreglos-lineales-vxt-210',
    description: 'Arreglo lineal 2x10", 1 Driver 3", 750W RMS',
    price: 19841.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'arreglos-lineales-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '018',
    name: 'VXT 206',
    slug: 'arreglos-lineales-vxt-206',
    description: '2 altavoces de 6.5", 1 de 1", 4,400W RMS',
    price: 7400.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'arreglos-lineales-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '019',
    name: 'VXT 110',
    slug: 'arreglos-lineales-vxt-110',
    description: '1 Altavoz coaxial de 10", 500W RMS',
    price: 11717.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'arreglos-lineales-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '020',
    name: 'BUMPER VXT 206',
    slug: 'arreglos-lineales-bumper-vxt-206',
    description: 'Soporte bumper de alta calidad para VXT 206',
    price: 2599.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'arreglos-lineales-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '021',
    name: 'BUMPER VXT 110',
    slug: 'arreglos-lineales-bumper-vxt-110',
    description: 'Soporte bumper de alta calidad para VXT 110',
    price: 3799.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'arreglos-lineales-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '022',
    name: 'BUMPER VXT 208',
    slug: 'arreglos-lineales-bumper-vxt-208',
    description: 'Accesorio para colgado de arreglo lineal',
    price: 5228.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'arreglos-lineales-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '023',
    name: 'BUMPER VXT 210',
    slug: 'arreglos-lineales-bumper-vxt-210',
    description: 'Accesorio para colgado de arreglo lineal VXT 210',
    price: 5228.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'arreglos-lineales-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '024',
    name: 'DSP 3.6',
    slug: 'arreglos-lineales-dsp-36',
    description: 'Procesador de audio 3 entradas, 6 salidas, filtros FIR',
    price: 9380.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'arreglos-lineales-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '025',
    name: 'BUMPER NOVA VXT',
    slug: 'arreglos-lineales-bumper-nova-vxt',
    description: 'Accesorio para colgado de arreglo lineal',
    price: 2333.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'arreglos-lineales-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '026',
    name: 'COOPER TWIN',
    slug: 'sistemas-de-audio-cooper-twin',
    description:
      'Sistema de audio activo-pasivo, sub de 10" con 2 satélites, USB y BT',
    price: 12012.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'sistemas-de-audio-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '027',
    name: 'AURA 12',
    slug: 'sistemas-de-audio-aura-12',
    description: 'Sistema audio sub 12" con satélite',
    price: 8605.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'sistemas-de-audio-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '028',
    name: 'XPECTRA 800',
    slug: 'sistemas-de-audio-xpectra-800',
    description: 'Sistema audio sub 12" con satélite',
    price: 10210.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'sistemas-de-audio-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '029',
    name: 'LA 800',
    slug: 'sistemas-de-audio-la-800',
    description: 'Sistema audio sub 18" + 2 satélites y 2 tripiés',
    price: 12920.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'sistemas-de-audio-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '030',
    name: 'BIG SU-HYPER',
    slug: 'sistemas-de-audio-big-su-hyper',
    description: 'Sistema audio sub 18" + 2 satélites y 2 tripiés',
    price: 13536.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'sistemas-de-audio-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '031',
    name: 'KWT 25',
    slug: 'sistemas-de-audio-kwt-25',
    description: '2 altavoces de 5" y 1 tweeter de 1" 280W RMS',
    price: 3520.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'sistemas-de-audio-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '032',
    name: 'KWS 210',
    slug: 'sistemas-de-audio-kws-210',
    description: '2 altavoces de 10" 800W RMS',
    price: 8599.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'sistemas-de-audio-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '033',
    name: '66SS',
    slug: 'sistemas-de-audio-66ss',
    description: 'Tubular para sistema de audio KW',
    price: 342.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'sistemas-de-audio-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '034',
    name: 'VSP15',
    slug: 'subwoofers-vsp15',
    description: 'Subwoofer de 15", 500W RMS, MDF',
    price: 6768.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'subwoofers-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '035',
    name: 'TERRA 15',
    slug: 'subwoofers-terra-15',
    description: 'Subwoofer de 15" 600W, RMS, MDF',
    price: 8103.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'subwoofers-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '036',
    name: 'VSP18',
    slug: 'subwoofers-vsp18',
    description: 'Subwoofer de 18", 900W RMS, MDF',
    price: 12114.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'subwoofers-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '037',
    name: 'TERRA 18',
    slug: 'subwoofers-terra-18',
    description: 'Subwoofer de 18" 900W RMS, MDF',
    price: 10826.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'subwoofers-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '038',
    name: 'VSP218',
    slug: 'subwoofers-vsp218',
    description: 'Subwoofer 2x18", 1500W RMS, con DSP configurable, MDF',
    price: 20900.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'subwoofers-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '048',
    name: 'LM-552',
    slug: 'microfonos-lm-552',
    description: 'Micrófono dinámico de mano con cable',
    price: 581.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'microfonos-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '049',
    name: 'LM-511',
    slug: 'microfonos-lm-511',
    description: 'Micrófono dinámico de mano con cable',
    price: 347.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'microfonos-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '050',
    name: 'LM-33C',
    slug: 'microfonos-lm-33c',
    description: 'Micrófono dinámico de mano con cable',
    price: 278.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'microfonos-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '051',
    name: 'LM-33D',
    slug: 'microfonos-lm-33d',
    description: 'Micrófono dinámico de mano con cable',
    price: 278.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'microfonos-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '052',
    name: 'LM-33E',
    slug: 'microfonos-lm-33e',
    description: 'Micrófono dinámico de mano con cable',
    price: 278.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'microfonos-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '053',
    name: 'V-302',
    slug: 'microfonos-v-302',
    description: 'Micrófono dinámico de mano con cable',
    price: 399.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'microfonos-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '054',
    name: 'V-304',
    slug: 'microfonos-v-304',
    description: 'Micrófono dinámico de mano con cable',
    price: 553.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'microfonos-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '055',
    name: 'V-309',
    slug: 'microfonos-v-309',
    description: 'Micrófono dinámico de mano con cable',
    price: 442.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'microfonos-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '056',
    name: 'V-101',
    slug: 'microfonos-v-101',
    description: 'Micrófono dinámico de mano con cable',
    price: 272.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'microfonos-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '057',
    name: 'V-103',
    slug: 'microfonos-v-103',
    description: 'Micrófono dinámico de mano con cable',
    price: 249.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'microfonos-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '060',
    name: 'PV-104',
    slug: 'microfonos-inalambricos-pv-104',
    description: 'Micrófono inalámbrico VHF',
    price: 1118.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'microfonos-inalambricos-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '061',
    name: 'PU-501',
    slug: 'microfonos-inalambricos-pu-501',
    description: 'Micrófono inalámbrico UHF',
    price: 2065.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'microfonos-inalambricos-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '062',
    name: 'PU-502',
    slug: 'microfonos-inalambricos-pu-502',
    description: 'Micrófono inalámbrico UHF',
    price: 1712.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'microfonos-inalambricos-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '063',
    name: 'PU-616',
    slug: 'microfonos-inalambricos-pu-616',
    description: 'Micrófono inalámbrico UHF',
    price: 3092.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'microfonos-inalambricos-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '064',
    name: 'UR-700',
    slug: 'microfonos-inalambricos-ur-700',
    description: 'Micrófono inalámbrico UHF',
    price: 3370.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'microfonos-inalambricos-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '065',
    name: 'PU-703',
    slug: 'microfonos-inalambricos-pu-703',
    description: 'Micrófono inalámbrico UHF',
    price: 2109.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'microfonos-inalambricos-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '066',
    name: 'PU-704',
    slug: 'microfonos-inalambricos-pu-704',
    description: 'Micrófono inalámbrico UHF',
    price: 2825.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'microfonos-inalambricos-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '067',
    name: 'PU-705',
    slug: 'microfonos-inalambricos-pu-705',
    description: 'Micrófono inalámbrico UHF',
    price: 2630.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'microfonos-inalambricos-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '068',
    name: 'PU-5500',
    slug: 'microfonos-inalambricos-pu-5500',
    description: 'Micrófono inalámbrico UHF 4pzas',
    price: 6461.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'microfonos-inalambricos-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '069',
    name: 'UR-690',
    slug: 'microfonos-inalambricos-ur-690',
    description: 'Micrófono inalámbrico UHF',
    price: 2984.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'microfonos-inalambricos-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '070',
    name: '502USB',
    slug: 'mezcladoras-502usb',
    description: 'Mezcladora 1ch mono + 2st USB',
    price: 1288.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'mezcladoras-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '071',
    name: 'PMX-120DSP',
    slug: 'mezcladoras-pmx-120dsp',
    description:
      'Mezcladora 8ch mono + 2st USB, EQ grafico de 7 bandas y procesador de efectos',
    price: 4851.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'mezcladoras-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '072',
    name: 'PMX-160DSP',
    slug: 'mezcladoras-pmx-160dsp',
    description:
      'Mezcladora 12ch mono + 2st USB, EQ grafico de 7 bandas y procesador de efectos',
    price: 5431.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'mezcladoras-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '073',
    name: 'SV 6 PRO',
    slug: 'mezcladoras-sv-6-pro',
    description:
      'Mezcladora 6 canales, ecualizador parametrico, ecualizador grafico, procesador de efectos',
    price: 3499,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'mezcladoras-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '074',
    name: 'SV 8 PRO',
    slug: 'mezcladoras-sv-8-pro',
    description:
      'Mezcladora 8 canales, ecualizador parametrico, ecualizador grafico, procesador de efectos',
    price: 4400.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'mezcladoras-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '075',
    name: 'SV 12 PRO',
    slug: 'mezcladoras-sv-12-pro',
    description:
      'Mezcladora 12 canales, ecualizador parametrico, ecualizador grafico, procesador de efectos',
    price: 5173.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'mezcladoras-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '076',
    name: 'FV 6',
    slug: 'mezcladoras-fv-6',
    description:
      'MEZCLADORA * 3 ENTRADAS XLR, 2 SALIDAS XLR, PROCESADOR DE EFECTOS',
    price: 2159.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'mezcladoras-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '077',
    name: 'FV 8',
    slug: 'mezcladoras-fv-8',
    description:
      'MEZCLADORA *5 ENTRADAS XLR, *2 SALIDAS XLR, PROCESADOR DE EFECTOS',
    price: 2468.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'mezcladoras-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '078',
    name: 'MV 12 PRO',
    slug: 'mezcladoras-mv-12-pro',
    description:
      'MEZCLADORA *8 ENTRADAS XLR, *2 SALIDAS XLR, *4 SALIDAS ASIGNABLES EN XLR',
    price: 7229.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'mezcladoras-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '079',
    name: 'MV 16 PRO',
    slug: 'mezcladoras-mv-16-pro',
    description:
      'MEZCLADORA *12 ENTRADAS XLR, *2 SALIDAS XLR, *4 SALIDAS ASIGNABLES',
    price: 8360.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'mezcladoras-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '080',
    name: 'MV 24 PRO',
    slug: 'mezcladoras-mv-24-pro',
    description:
      'MEZCLADORA *20 ENTRADAS XLR, *2 SALIDAS XLR, *4 SALIDAS ASIGNABLES',
    price: 12206.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'mezcladoras-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '081-smv-1',
    name: 'SMV-1',
    slug: 'accesorios-gs-305',
    description: 'Soporte para micrófono reforzado con boom, a 2 vias',
    price: 443.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'accesorios-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '081-smv-2',
    name: 'SMV-2',
    slug: 'accesorios-gs-305',
    description: 'Soporte para micrófono reforzado con boom',
    price: 396.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'accesorios-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '081-smv-3',
    name: 'SMV-3',
    slug: 'accesorios-gs-305',
    description: 'Soporte para micrófono reforzado con boom',
    price: 524.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'accesorios-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '081-SPV-1',
    name: 'SPV-1',
    slug: 'accesorios-gs-305',
    description: 'Poste para subwoofer, capacidad de carga máxima 50kg',
    price: 210.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'accesorios-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '081-TV-1',
    name: 'SPV-1',
    slug: 'accesorios-gs-305',
    description: 'TRIPIE REFORXADO PARA BAFLE, CARGA MAXIMA 60 KG',
    price: 455.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'accesorios-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '081',
    name: 'GS-305',
    slug: 'accesorios-gs-305',
    description: 'Atril guitarra acústica/eléctrica/bajo',
    price: 173.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'accesorios-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '082',
    name: 'BGS-101',
    slug: 'accesorios-bgs-101',
    description: 'Banco pie guitarrista',
    price: 122.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'accesorios-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '083',
    name: 'KSS-101',
    slug: 'accesorios-kss-101',
    description: 'Asiento ajustable pianista',
    price: 354.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'accesorios-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '084',
    name: 'STM-101',
    slug: 'accesorios-stm-101',
    description: 'Tripié para micrófono de mesa',
    price: 135.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'accesorios-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '086',
    name: 'XLRMF1',
    slug: 'cables-xlrmf1',
    description: 'Cable audio XLR 1m',
    price: 55.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'cables-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '087',
    name: 'XLRMF3',
    slug: 'cables-xlrmf3',
    description: 'Cable audio XLR 3m',
    price: 62.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'cables-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '088',
    name: 'XLRMF6',
    slug: 'cables-xlrmf6',
    description: 'Cable audio XLR 6m',
    price: 83.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'cables-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '089',
    name: 'XLRMF10',
    slug: 'cables-xlrmf10',
    description: 'Cable audio XLR 10m',
    price: 108.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'cables-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '090',
    name: 'XLRHMF1',
    slug: 'cables-xlrhmf1',
    description: 'Cable XLR profesional 1m',
    price: 69.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'cables-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '091',
    name: 'XLRHMF3',
    slug: 'cables-xlrhmf3',
    description: 'Cable de audio XLR conector profesional 3m',
    price: 78.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'cables-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '092',
    name: 'XLRHMF6',
    slug: 'cables-xlrhmf6',
    description: 'Cable de audio XLR conector profesional 6m',
    price: 116.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'cables-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '093',
    name: 'XLRHMF10',
    slug: 'cables-xlrhmf10',
    description: 'Cable de audio XLR conector profesional 10m',
    price: 158.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'cables-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '094',
    name: 'SPK5',
    slug: 'cables-spk5',
    description: 'CABLE PARA BAFLE SPEAKON 16GA 5M',
    price: 78.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'cables-category',
    features: [''],
    videoUrl: '',
  },
  {
    id: '095',
    name: 'SPKH5',
    slug: 'cables-spkh5',
    description: 'CABLE PARA BAFLE SPEAKON 16GA 10m',
    price: 109.0,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'cables-category',
    features: [''],
    videoUrl: '',
  },
  // ########################
  // catalogo 2
  // ########################
  {
    id: '001-JZG-15P',
    name: 'JZG-15P',
    slug: 'jzg-15p',
    description: 'JZG-15P',
    price: 4800.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: '002-JZG XDS 915B',
    name: 'JZG XDS 915B',
    slug: 'jzg-xds-915b',
    description: 'JZG XDS 915B',
    price: 9990.0,
    coverImage:
      'https://res.cloudinary.com/dbbw5ppe1/image/upload/v1750739826/JZG-XDS-915B-1_rwi31d.webp',
    images: [
      'https://res.cloudinary.com/dbbw5ppe1/image/upload/v1750739826/JZG-XDS-915B-1_rwi31d.webp',
      'https://res.cloudinary.com/dbbw5ppe1/image/upload/v1750739826/JZG-XDS-915B-2_kw5kgp.webp',
      'https://res.cloudinary.com/dbbw5ppe1/image/upload/v1750739826/JZG-XDS-915B-3_nisqjb.webp',
      'https://res.cloudinary.com/dbbw5ppe1/image/upload/v1750739826/JZG-XDS-915B-4_ydl8pw.webp',
    ],
    categoryId: 'bafles-category',
    features: [],
    videoUrl: '',
  },
  {
    id: '003-JZG XDS 918SB',
    name: 'JZG XDS 918SB',
    slug: 'jzg-xds-918sb',
    description: 'JZG XDS 918SB',
    price: 13440.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: '004-JZG XDS 9218SB',
    name: 'JZG XDS 9218SB',
    slug: 'jzg-xds-9218sb',
    description: 'JZG XDS 9218SB',
    price: 20280.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: '005-JZG SET 4 RUEDAS',
    name: 'JZG SET 4 RUEDAS',
    slug: 'jzg-set-4-ruedas',
    description: 'JZG SET 4 RUEDAS',
    price: 600.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: '006-JZG XDS 1000SB',
    name: 'JZG XDS 1000SB',
    slug: 'jzg-xds-1000sb',
    description: 'JZG XDS 1000SB',
    price: 13440.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: '007-EDS15P',
    name: 'EDS15P',
    slug: 'eds15p',
    description: 'EDS15P',
    price: 6960.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: '008-EDS18P',
    name: 'EDS18P',
    slug: 'eds18p',
    description: 'EDS18P',
    price: 9920.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: '009-EDS218P',
    name: 'EDS218P',
    slug: 'eds218p',
    description: 'EDS218P',
    price: 19920.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: '010-JZG SP/STAND 1.80M',
    name: 'JZG SP/STAND 1.80M',
    slug: 'jzg-sp-stand-1-80m',
    description: 'JZG SP/STAND 1.80M',
    price: 600.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: '011-JZG-STAND/.80M',
    name: 'JZG-STAND/.80M',
    slug: 'jzg-stand-0-80m',
    description: 'JZG-STAND/.80M',
    price: 460.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: '012-JZG WALL STAND',
    name: 'JZG WALL STAND',
    slug: 'jzg-wall-stand',
    description: 'JZG WALL STAND',
    price: 400.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: '013-ETS SP/STAND 1.80M',
    name: 'ETS SP/STAND 1.80M',
    slug: 'ets-sp-stand-1-80m',
    description: 'ETS SP/STAND 1.80M',
    price: 600.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: '014-ETS-STAND/.80M',
    name: 'ETS-STAND/.80M',
    slug: 'ets-stand-0-80m',
    description: 'ETS-STAND/.80M',
    price: 460.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: '015-JZG-MLA-210A',
    name: 'JZG-MLA-210A',
    slug: 'jzg-mla-210a',
    description: 'JZG-MLA-210A',
    price: 23850.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: '016-JZG-615AP',
    name: 'JZG-615AP',
    slug: 'jzg-615ap',
    description: 'JZG-615AP',
    price: 16500.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: '017-JZG 2x18APB',
    name: 'JZG 2x18APB',
    slug: 'jzg-2x18apb',
    description: 'JZG 2x18APB',
    price: 29150.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: '017-FLYING KIT',
    name: 'FLYING KIT',
    slug: 'flying-kit',
    description: 'FLYING KIT',
    price: 7600.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: '018-DSC 24X DSP',
    name: 'DSC 24X DSP',
    slug: 'dsc-24x-dsp',
    description: 'DSC 24X DSP',
    price: 7300.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: '019-DSC 4800 DSP',
    name: 'DSC 4800 DSP',
    slug: 'dsc-4800-dsp',
    description: 'DSC 4800 DSP',
    price: 14514.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: '020-ELT118A',
    name: 'ELT118A',
    slug: 'elt118a',
    description: 'ELT118A',
    price: 11200.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: '021-ELT15ADS',
    name: 'ELT15ADS',
    slug: 'elt15ads',
    description: 'ELT15ADS',
    price: 9640.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },

  // ##############
  // ##############
  // ##############
  // BOCINAS
  {
    id: '00-JZG-1570',
    name: 'JZG-1570',
    price: 1465.0,
    description: 'JZG-1570',
    slug: 'jzg-1570',
    coverImage: '',
    images: [],
    categoryId: 'bafles-category',
    features: [],
    videoUrl: '',
  },
  {
    id: '01-JZG 2040',
    name: 'JZG 2040',
    price: 800.0,
    description: 'JZG 2040',
    slug: 'jzg-2040',
    coverImage: '',
    images: [],
    categoryId: 'bafles-category',
    features: [],
    videoUrl: '',
  },
  {
    id: '00-JZG 2550',
    name: 'JZG 2550',
    price: 1000.0,
    description: 'JZG 2550',
    slug: 'jzg-2550',
    coverImage: '',
    images: [],
    categoryId: 'bafles-category',
    features: [],
    videoUrl: '',
  },
  {
    id: '02-JZG 3050',
    name: 'JZG 3050',
    price: 1420.0,
    description: 'JZG 3050',
    slug: 'jzg-3050',
    coverImage: '',
    images: [],
    categoryId: 'bafles-category',
    features: [],
    videoUrl: '',
  },
  {
    id: '03-JZG 38100',
    name: 'JZG 38100',
    price: 2200.0,
    description: 'JZG 38100',
    slug: 'jzg-38100',
    coverImage: '',
    images: [],
    categoryId: 'bafles-category',
    features: [],
    videoUrl: '',
  },
  {
    id: '04-JZG 18ES',
    name: 'JZG 18ES',
    price: 3900.0,
    description: 'JZG 18ES',
    slug: 'jzg-18es',
    coverImage: '',
    images: [],
    categoryId: 'bafles-category',
    features: [],
    videoUrl: '',
  },
  {
    id: '05-JZG-18 PA',
    name: 'JZG-18 PA',
    price: 3400.0,
    description: 'JZG-18 PA',
    slug: 'jzg-18-pa',
    coverImage: '',
    images: [],
    categoryId: 'bafles-category',
    features: [],
    videoUrl: '',
  },
  {
    id: '06-JZG 6.5X',
    name: 'JZG 6.5X',
    price: 630.0,
    description: 'JZG 6.5X',
    slug: 'jzg-65x',
    coverImage: '',
    images: [],
    categoryId: 'bafles-category',
    features: [],
    videoUrl: '',
  },
  {
    id: '07-JZG 8X',
    name: 'JZG 8X',
    price: 920.0,
    description: 'JZG 8X',
    slug: 'jzg-8x',
    coverImage: '',
    images: [],
    categoryId: 'bafles-category',
    features: [],
    videoUrl: '',
  },
  {
    id: '08-JZG 8X2',
    name: 'JZG 8X2',
    price: 985.0,
    description: 'JZG 8X2',
    slug: 'jzg-8x2',
    coverImage: '',
    images: [],
    categoryId: 'bafles-category',
    features: [],
    videoUrl: '',
  },
  {
    id: '09-JZG 10X3',
    name: 'JZG 10X3',
    price: 1950.0,
    description: 'JZG 10X3',
    slug: 'jzg-10x3',
    coverImage: '',
    images: [],
    categoryId: 'bafles-category',
    features: [],
    videoUrl: '',
  },
  {
    id: '10-JZG 12X3',
    name: 'JZG 12X3',
    price: 2400.0,
    description: 'JZG 12X3',
    slug: 'jzg-12x3',
    coverImage: '',
    images: [],
    categoryId: 'bafles-category',
    features: [],
    videoUrl: '',
  },
  {
    id: '11-JZG 15X3',
    name: 'JZG 15X3',
    price: 2700.0,
    description: 'JZG 15X3',
    slug: 'jzg-15x3',
    coverImage: '',
    images: [],
    categoryId: 'bafles-category',
    features: [],
    videoUrl: '',
  },
  {
    id: '12-JZG 18X4BC',
    name: 'JZG 18X4BC',
    price: 4800.0,
    description: 'JZG 18X4BC',
    slug: 'jzg-18x4bc',
    coverImage: '',
    images: [],
    categoryId: 'bafles-category',
    features: [],
    videoUrl: '',
  },
  {
    id: '13-JZG 18X4RF',
    name: 'JZG 18X4RF',
    price: 4900.0,
    description: 'JZG 18X4RF',
    slug: 'jzg-18x4rf',
    coverImage: '',
    images: [],
    categoryId: 'bafles-category',
    features: [],
    videoUrl: '',
  },
  {
    id: '14-JZG 21X45 RF',
    name: 'JZG 21X45 RF',
    price: 7920.0,
    description: 'JZG 21X45 RF',
    slug: 'jzg-21x45-rf',
    coverImage: '',
    images: [],
    categoryId: 'bafles-category',
    features: [],
    videoUrl: '',
  },
  {
    id: '15-JZG 18X4EG',
    name: 'JZG 18X4EG',
    price: 4740.0,
    description: 'JZG 18X4EG',
    slug: 'jzg-18x4eg',
    coverImage: '',
    images: [],
    categoryId: 'bafles-category',
    features: [],
    videoUrl: '',
  },
  {
    id: '16-JZG 18X6 PW',
    name: 'JZG 18X6 PW',
    price: 7800.0,
    description: 'JZG 18X6 PW',
    slug: 'jzg-18x6-pw',
    coverImage: '',
    images: [],
    categoryId: 'bafles-category',
    features: [],
    videoUrl: '',
  },
  {
    id: '17-JZG 21X6 PW',
    name: 'JZG 21X6 PW',
    price: 10600.0,
    description: 'JZG 21X6 PW',
    slug: 'jzg-21x6-pw',
    coverImage: '',
    images: [],
    categoryId: 'bafles-category',
    features: [],
    videoUrl: '',
  },
  {
    id: '00-JLS-1880',
    name: 'JLS-1880',
    price: 2600.0,
    description: 'JLS-1880',
    slug: 'jls-1880',
    coverImage: '',
    images: [],
    categoryId: 'bafles-category',
    features: [],
    videoUrl: '',
  },
  {
    id: '00-JLS PA-18',
    name: 'JLS PA-18',
    price: 3250.0,
    description: 'JLS PA-18',
    slug: 'jls-pa-18',
    coverImage: '',
    images: [],
    categoryId: 'bafles-category',
    features: [],
    videoUrl: '',
  },
  {
    id: '00-JZG-21NSW153',
    name: 'JZG-21NSW153',
    price: 14280.0,
    description: 'JZG-21NSW153',
    slug: 'jzg-21nsw153',
    coverImage: '',
    images: [],
    categoryId: 'bafles-category',
    features: [],
    videoUrl: '',
  },
  {
    id: '00-JZG18NSW115',
    name: 'JZG18NSW115',
    price: 7860.0,
    description: 'JZG18NSW115',
    slug: 'jzg18nsw115',
    coverImage: '',
    images: [],
    categoryId: 'bafles-category',
    features: [],
    videoUrl: '',
  },
  {
    id: '00-JZG-15NSW115',
    name: 'JZG-15NSW115',
    price: 7140.0,
    description: 'JZG-15NSW115',
    slug: 'jzg-15nsw115',
    coverImage: '',
    images: [],
    categoryId: 'bafles-category',
    features: [],
    videoUrl: '',
  },
  {
    id: '00-JZG-12NSW115',
    name: 'JZG-12NSW115',
    price: 6480.0,
    description: 'JZG-12NSW115',
    slug: 'jzg-12nsw115',
    coverImage: '',
    images: [],
    categoryId: 'bafles-category',
    features: [],
    videoUrl: '',
  },
  {
    id: '00-JZG-10Neo75',
    name: 'JZG-10Neo75',
    price: 3180.0,
    description: 'JZG-10Neo75',
    slug: 'jzg-10neo75',
    coverImage: '',
    images: [],
    categoryId: 'bafles-category',
    features: [],
    videoUrl: '',
  },
  {
    id: '00-JZG-12NEO75',
    name: 'JZG-12NEO75',
    price: 3480.0,
    description: 'JZG-12NEO75',
    slug: 'jzg-12neo75',
    coverImage: '',
    images: [],
    categoryId: 'bafles-category',
    features: [],
    videoUrl: '',
  },
  {
    id: '00-JZG-tw5800',
    name: 'JZG-tw5800',
    price: 1080.0,
    description: 'JZG-tw5800',
    slug: 'jzg-tw5800',
    coverImage: '',
    images: [],
    categoryId: 'bafles-category',
    features: [],
    videoUrl: '',
  },
  // ##############
  // ##############
  // ##############
  // Driver CROSSVR
  {
    id: 'JZG-350',
    name: 'JZG 350',
    description: '',
    slug: 'jzg-350',
    price: 620.0,
    coverImage: '',
    images: [],
    categoryId: 'bafles-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'JZG-400',
    name: 'JZG 400',
    description: '',
    slug: 'jzg-400',
    price: 800.0,
    coverImage: '',
    images: [],
    categoryId: 'bafles-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'JZG-500',
    name: 'JZG 500',
    description: '',
    slug: 'jzg-500',
    price: 1090.0,
    coverImage: '',
    images: [],
    categoryId: 'bafles-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'JZG-450-PL',
    name: 'JZG 450 PL',
    description: '',
    slug: 'jzg-450-pl',
    price: 880.0,
    coverImage: '',
    images: [],
    categoryId: 'bafles-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'JZG-550-PL',
    name: 'JZG 550 PL',
    description: '',
    slug: 'jzg-550-pl',
    price: 1170.0,
    coverImage: '',
    images: [],
    categoryId: 'bafles-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'JZG-700-PL',
    name: 'JZG 700 PL',
    description: '',
    slug: 'jzg-700-pl',
    price: 2100.0,
    coverImage: '',
    images: [],
    categoryId: 'bafles-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'JZG-750-PL',
    name: 'JZG 750 PL',
    description: '',
    slug: 'jzg-750-pl',
    price: 2620.0,
    coverImage: '',
    images: [],
    categoryId: 'bafles-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'JZG-2-WAY-C-CROSSOVER',
    name: 'JZG 2 WAY C-CROSSOVER',
    description: '',
    slug: 'jzg-2-way-c-crossover',
    price: 800.0,
    coverImage: '',
    images: [],
    categoryId: 'bafles-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'JZG-3-WAY-C-CROSSOVER',
    name: 'JZG 3 WAY C-CROSSOVER',
    description: '',
    slug: 'jzg-3-way-c-crossover',
    price: 850.0,
    coverImage: '',
    images: [],
    categoryId: 'bafles-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'JZG-TW-2.8',
    name: 'JZG TW 2.8',
    description: '',
    slug: 'jzg-tw-2-8',
    price: 420.0,
    coverImage: '',
    images: [],
    categoryId: 'bafles-category',
    features: [],
    videoUrl: '',
  },

  // ##############
  // ##############
  // ##############
  // Diafragma

  {
    id: 'jzg-d-350',
    name: 'JZG D 350',
    slug: 'jzg-d-350',
    description: '',
    price: 165.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-d-400',
    name: 'JZG D 400',
    slug: 'jzg-d-400',
    description: '',
    price: 200.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-d-450',
    name: 'JZG D 450',
    slug: 'jzg-d-450',
    description: '',
    price: 250.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-d-500',
    name: 'JZG D 500',
    slug: 'jzg-d-500',
    description: '',
    price: 260.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-d-550',
    name: 'JZG D 550',
    slug: 'jzg-d-550',
    description: '',
    price: 300.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-d-700',
    name: 'JZG D 700',
    slug: 'jzg-d-700',
    description: '',
    price: 500.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-d-750-pa',
    name: 'JZG D 750 PA',
    slug: 'jzg-d-750-pa',
    description: '',
    price: 500.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-d-2445-rf',
    name: 'JZG D 2445 RF',
    slug: 'jzg-d-2445-rf',
    description: '',
    price: 670.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-d-rcf',
    name: 'JZG D RCF',
    slug: 'jzg-d-rcf',
    description: '',
    price: 500.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-d-b&c',
    name: 'JZG D B&C',
    slug: 'jzg-d-b&c',
    description: '',
    price: 500.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-d-eig',
    name: 'JZG D EIG',
    slug: 'jzg-d-eig',
    description: '',
    price: 500.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-d-tw57re',
    name: 'JZG D TW57RE',
    slug: 'jzg-d-tw57re',
    description: '',
    price: 200.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-d-tw57pl',
    name: 'JZG D TW57PL',
    slug: 'jzg-d-tw57pl',
    description: '',
    price: 240.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-d-2412',
    name: 'JZG D 2412',
    slug: 'jzg-d-2412',
    description: '',
    price: 100.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-d-2412-a',
    name: 'JZG D 2412 A',
    slug: 'jzg-d-2412-a',
    description: '',
    price: 105.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-d-2416-26',
    name: 'JZG D 2416-26',
    slug: 'jzg-d-2416-26',
    description: '',
    price: 170.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-d-2416-26sb',
    name: 'JZG D 2416-26SB',
    slug: 'jzg-d-2416-26sb',
    description: '',
    price: 175.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-d-2418',
    name: 'JZG D 2418',
    slug: 'jzg-d-2418',
    description: '',
    price: 140.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-d-emcbr',
    name: 'JZG D EMCBR',
    slug: 'jzg-d-emcbr',
    description: '',
    price: 180.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-d-450-sb',
    name: 'JZG D 450 SB',
    slug: 'jzg-d-450-sb',
    description: '',
    price: 175.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-d-14xt',
    name: 'JZG D 14XT',
    slug: 'jzg-d-14xt',
    description: '',
    price: 175.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-d-210-sl',
    name: 'JZG D 210 SL',
    slug: 'jzg-d-210-sl',
    description: '',
    price: 175.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-d-22xtsb',
    name: 'JZG D 22XTSB',
    slug: 'jzg-d-22xtsb',
    description: '',
    price: 190.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jls-d-rcf',
    name: 'JLS D RCF',
    slug: 'jls-d-rcf',
    description: '',
    price: 315.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jls-d-b&c',
    name: 'JLS D B&C',
    slug: 'jls-d-b&c',
    description: '',
    price: 315.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jls-d-eig',
    name: 'JLS D EIG',
    slug: 'jls-d-eig',
    description: '',
    price: 315.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jls-d-750-pa',
    name: 'JLS D 750 PA',
    slug: 'jls-d-750-pa',
    description: '',
    price: 315.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jls-d-2445-rf',
    name: 'JLS D 2445 RF',
    slug: 'jls-d-2445-rf',
    description: '',
    price: 600.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jls-d-tw57re',
    name: 'JLS D TW57RE',
    slug: 'jls-d-tw57re',
    description: '',
    price: 150.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jls-d-tw57pl',
    name: 'JLS D TW57PL',
    slug: 'jls-d-tw57pl',
    description: '',
    price: 195.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jls-d-2416-26',
    name: 'JLS D 2416-26',
    slug: 'jls-d-2416-26',
    description: '',
    price: 140.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jls-d-emcbr',
    name: 'JLS D EMCBR',
    slug: 'jls-d-emcbr',
    description: '',
    price: 140.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jls-d-450-sb',
    name: 'JLS D 450 SB',
    slug: 'jls-d-450-sb',
    description: '',
    price: 130.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jls-d-14xt',
    name: 'JLS D 14XT',
    slug: 'jls-d-14xt',
    description: '',
    price: 130.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jls-d-210-sl',
    name: 'JLS D 210 SL',
    slug: 'jls-d-210-sl',
    description: '',
    price: 130.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jls-d-22xtsb',
    name: 'JLS D 22XTSB',
    slug: 'jls-d-22xtsb',
    description: '',
    price: 150.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },

  // ##############
  // ##############
  // ##############
  // Conector
  // ##############
  // ##############
  // ##############

  {
    id: 'jzg-plug-6087',
    name: 'JZG PLUG 6087',
    description: '',
    slug: 'jzg-plug-6087',
    price: 28.0,
    coverImage: '',
    images: [],
    categoryId: 'accesorios-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-plug-st82',
    name: 'JZG PLUG ST82',
    description: '',
    slug: 'jzg-plug-st82',
    price: 29.0,
    coverImage: '',
    images: [],
    categoryId: 'accesorios-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-plug-1-4-c-resorte',
    name: 'JZG PLUG 1/4 C-RESORTE',
    description: '',
    slug: 'jzg-plug-1-4-c-resorte',
    price: 24.0,
    coverImage: '',
    images: [],
    categoryId: 'accesorios-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-plug-1-4-c-resorte-gold',
    name: 'JZG PLUG 1/4 C-RESORTE GOLD',
    description: '',
    slug: 'jzg-plug-1-4-c-resorte-gold',
    price: 29.0,
    coverImage: '',
    images: [],
    categoryId: 'accesorios-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-plug-sq',
    name: 'JZG PLUG SQ',
    description: '',
    slug: 'jzg-plug-sq',
    price: 26.0,
    coverImage: '',
    images: [],
    categoryId: 'accesorios-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-plug-6085',
    name: 'JZG PLUG 6085',
    description: '',
    slug: 'jzg-plug-6085',
    price: 27.0,
    coverImage: '',
    images: [],
    categoryId: 'accesorios-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-xlr16m',
    name: 'JZG XLR16(M)',
    description: '',
    slug: 'jzg-xlr16m',
    price: 40.0,
    coverImage: '',
    images: [],
    categoryId: 'accesorios-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-xlr15f',
    name: 'JZG XLR15(F)',
    description: '',
    slug: 'jzg-xlr15f',
    price: 40.0,
    coverImage: '',
    images: [],
    categoryId: 'accesorios-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-xlr-m',
    name: 'JZG XLR (M)',
    description: '',
    slug: 'jzg-xlr-m',
    price: 40.0,
    coverImage: '',
    images: [],
    categoryId: 'accesorios-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-xlr-f',
    name: 'JZG XLR (F)',
    description: '',
    slug: 'jzg-xlr-f',
    price: 40.0,
    coverImage: '',
    images: [],
    categoryId: 'accesorios-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-35-jumbo-stereo',
    name: 'JZG 3.5 JUMBO STEREO',
    description: '',
    slug: 'jzg-35-jumbo-stereo',
    price: 32.0,
    coverImage: '',
    images: [],
    categoryId: 'accesorios-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-35-jumbo-mono',
    name: 'JZG 3.5 JUMBO MONO',
    description: '',
    slug: 'jzg-35-jumbo-mono',
    price: 27.0,
    coverImage: '',
    images: [],
    categoryId: 'accesorios-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-term-008',
    name: 'JZG TERM 008',
    description: '',
    slug: 'jzg-term-008',
    price: 26.0,
    coverImage: '',
    images: [],
    categoryId: 'accesorios-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-femre-spk',
    name: 'JZG FEMRE SPK',
    description: '',
    slug: 'jzg-femre-spk',
    price: 27.0,
    coverImage: '',
    images: [],
    categoryId: 'accesorios-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-rca--r',
    name: 'JZG RCA ( R)',
    description: '',
    slug: 'jzg-rca--r',
    price: 32.0,
    coverImage: '',
    images: [],
    categoryId: 'accesorios-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-rca-b',
    name: 'JZG RCA (B)',
    description: '',
    slug: 'jzg-rca-b',
    price: 32.0,
    coverImage: '',
    images: [],
    categoryId: 'accesorios-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-banana',
    name: 'JZG BANANA',
    description: '',
    slug: 'jzg-banana',
    price: 62.0,
    coverImage: '',
    images: [],
    categoryId: 'accesorios-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-spk-007',
    name: 'JZG SPK 007',
    description: '',
    slug: 'jzg-spk-007',
    price: 43.0,
    coverImage: '',
    images: [],
    categoryId: 'accesorios-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jls-plug-78',
    name: 'JLS PLUG 78',
    description: '',
    slug: 'jls-plug-78',
    price: 21.0,
    coverImage: '',
    images: [],
    categoryId: 'accesorios-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jls-plug-63-c--resorte',
    name: 'JLS PLUG 6.3 C/ RESORTE',
    description: '',
    slug: 'jls-plug-63-c--resorte',
    price: 21.0,
    coverImage: '',
    images: [],
    categoryId: 'accesorios-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jls-plug-6057',
    name: 'JLS PLUG 6057',
    description: '',
    slug: 'jls-plug-6057',
    price: 22.0,
    coverImage: '',
    images: [],
    categoryId: 'accesorios-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jls-plug-80b',
    name: 'JLS PLUG 80(B)',
    description: '',
    slug: 'jls-plug-80b',
    price: 21.0,
    coverImage: '',
    images: [],
    categoryId: 'accesorios-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jls-plug-80-r',
    name: 'JLS PLUG 80( R)',
    description: '',
    slug: 'jls-plug-80-r',
    price: 21.0,
    coverImage: '',
    images: [],
    categoryId: 'accesorios-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jls-rca-cp',
    name: 'JLS RCA CP',
    description: '',
    slug: 'jls-rca-cp',
    price: 23.0,
    coverImage: '',
    images: [],
    categoryId: 'accesorios-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jls-xlr-03f-b',
    name: 'JLS XLR 03(F) B',
    description: '',
    slug: 'jls-xlr-03f-b',
    price: 23.0,
    coverImage: '',
    images: [],
    categoryId: 'accesorios-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jls-xlr-03-f-r',
    name: 'JLS XLR 03 (F) R',
    description: '',
    slug: 'jls-xlr-03-f-r',
    price: 24.0,
    coverImage: '',
    images: [],
    categoryId: 'accesorios-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jls-xlr-04-m-r',
    name: 'JLS XLR 04 (M) R',
    description: '',
    slug: 'jls-xlr-04-m-r',
    price: 23.0,
    coverImage: '',
    images: [],
    categoryId: 'accesorios-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jls-xlr-04-m-b',
    name: 'JLS XLR 04 (M) B',
    description: '',
    slug: 'jls-xlr-04-m-b',
    price: 24.0,
    coverImage: '',
    images: [],
    categoryId: 'accesorios-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jls-term-005',
    name: 'JLS TERM 005',
    description: '',
    slug: 'jls-term-005',
    price: 29.0,
    coverImage: '',
    images: [],
    categoryId: 'accesorios-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jls-femcu-spk',
    name: 'JLS FEMCU SPK',
    description: '',
    slug: 'jls-femcu-spk',
    price: 21.0,
    coverImage: '',
    images: [],
    categoryId: 'accesorios-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jls-403-7p',
    name: 'JLS 403 7P',
    description: '',
    slug: 'jls-403-7p',
    price: 35.0,
    coverImage: '',
    images: [],
    categoryId: 'accesorios-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jls-spk-003',
    name: 'JLS SPK 003',
    description: '',
    slug: 'jls-spk-003',
    price: 32.0,
    coverImage: '',
    images: [],
    categoryId: 'accesorios-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-exhibidor',
    name: 'JZG EXHIBIDOR',
    description: '',
    slug: 'jzg-exhibidor',
    price: 700.0,
    coverImage: '',
    images: [],
    categoryId: 'accesorios-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jls-exhibidor',
    name: 'JLS EXHIBIDOR',
    description: '',
    slug: 'jls-exhibidor',
    price: 500.0,
    coverImage: '',
    images: [],
    categoryId: 'accesorios-category',
    features: [],
    videoUrl: '',
  },

  // ##############
  // ##############
  // ##############
  // CABLES
  // ##############
  // ##############
  // ##############
  {
    id: 'JZG MIC 1.5',
    name: 'JZG MIC 1.5',
    description: '',
    slug: 'jzg-mic-1-5',
    price: 200,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'JZG MIC 3M',
    name: 'JZG MIC 3M',
    description: '',
    slug: 'jzg-mic-3m',
    price: 245,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'JZG MIC 6M',
    name: 'JZG MIC 6M',
    description: '',
    slug: 'jzg-mic-6m',
    price: 320,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'JZG MIC 10M',
    name: 'JZG MIC 10M',
    description: '',
    slug: 'jzg-mic-10m',
    price: 400,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'JZG MIC 15M',
    name: 'JZG MIC 15M',
    description: '',
    slug: 'jzg-mic-15m',
    price: 500,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'JZG MIC 20M',
    name: 'JZG MIC 20M',
    description: '',
    slug: 'jzg-mic-20m',
    price: 640,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'JZG-HIGH IMP 1.5M',
    name: 'JZG HIGH IMP 1.5M',
    description: '',
    slug: 'jzg-high-imp-1-5m',
    price: 195,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'JZG-HIGH IMP 3M',
    name: 'JZG HIGH IMP 3M',
    description: '',
    slug: 'jzg-high-imp-3m',
    price: 240,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'JZG-HIGH IMP 6M',
    name: 'JZG HIGH IMP 6M',
    description: '',
    slug: 'jzg-high-imp-6m',
    price: 315,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'JZG-HIGH IMP 10M',
    name: 'JZG HIGH IMP 10M',
    description: '',
    slug: 'jzg-high-imp-10m',
    price: 385,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'JZG-HIGH IMP 15M',
    name: 'JZG HIGH IMP 15M',
    description: '',
    slug: 'jzg-high-imp-15m',
    price: 490,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'JZG-PATCH 1.5M',
    name: 'JZG PATCH 1.5M',
    description: '',
    slug: 'jzg-patch-1-5m',
    price: 195,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'JZG-PATCH 3M',
    name: 'JZG PATCH 3M',
    description: '',
    slug: 'jzg-patch-3m',
    price: 240,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'JZG-PATCH 6M',
    name: 'JZG PATCH 6M',
    description: '',
    slug: 'jzg-patch-6m',
    price: 315,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'JZG-PATCH 10M',
    name: 'JZG PATCH 10M',
    description: '',
    slug: 'jzg-patch-10m',
    price: 385,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'JZG-INST 1.5M',
    name: 'JZG INST 1.5M',
    description: '',
    slug: 'jzg-inst-1-5m',
    price: 195,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'JZG-INST 3M',
    name: 'JZG INST 3M',
    description: '',
    slug: 'jzg-inst-3m',
    price: 240,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'JZG-INST 6M',
    name: 'JZG INST 6M',
    description: '',
    slug: 'jzg-inst-6m',
    price: 315,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'JZG-INST 10M',
    name: 'JZG INST 10M',
    description: '',
    slug: 'jzg-inst-10m',
    price: 385,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'JZG-DJ*1 1.5M',
    name: 'JZG DJ*1 1.5M',
    description: '',
    slug: 'jzg-dj1-1-5m',
    price: 170,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'JZG-DJ*1 3M',
    name: 'JZG DJ*1 3M',
    description: '',
    slug: 'jzg-dj1-3m',
    price: 210,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'JZG-DJ*2 1.5M',
    name: 'JZG DJ*2 1.5M',
    description: '',
    slug: 'jzg-dj2-1-5m',
    price: 170,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'JZG-DJ*2 3M',
    name: 'JZG DJ*2 3M',
    description: '',
    slug: 'jzg-dj2-3m',
    price: 210,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'JZG-DJ*3 1.5M',
    name: 'JZG DJ*3 1.5M',
    description: '',
    slug: 'jzg-dj3-1-5m',
    price: 170,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'JZG-DJ*3 3M',
    name: 'JZG DJ*3 3M',
    description: '',
    slug: 'jzg-dj3-3m',
    price: 210,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'JZG-DJ*4 1.5M',
    name: 'JZG DJ*4 1.5M',
    description: '',
    slug: 'jzg-dj4-1-5m',
    price: 260,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'JZG-DJ*4 3M',
    name: 'JZG DJ*4 3M',
    description: '',
    slug: 'jzg-dj4-3m',
    price: 350,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'JZG-DJ*5 3.5/3.5',
    name: 'JZG DJ*5 3.5/3.5',
    description: '',
    slug: 'jzg-dj5-3-5',
    price: 170,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'JZG SPK 14 AWG',
    name: 'JZG SPK 14 AWG',
    description: '',
    slug: 'jzg-spk-14-awg',
    price: 2150,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'JLS 2X24 AWG',
    name: 'JLS 2X24 AWG',
    description: '',
    slug: 'jls-2x24-awg',
    price: 1150,
    coverImage: '/images/bafles.webp',
    images: ['/images/bafles.webp'],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'auto-001',
    name: 'JLS MIC 1.5',
    slug: 'jls-mic-1-5',
    description: '',
    price: 150.0,
    coverImage: '/images/no-image.webp',
    images: [],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'auto-002',
    name: 'JLS MIC 3M',
    slug: 'jls-mic-3m',
    description: '',
    price: 170.0,
    coverImage: '/images/no-image.webp',
    images: [],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'auto-003',
    name: 'JLS MIC 6M',
    slug: 'jls-mic-6m',
    description: '',
    price: 220.0,
    coverImage: '/images/no-image.webp',
    images: [],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'auto-004',
    name: 'JLS MIC 10M',
    slug: 'jls-mic-10m',
    description: '',
    price: 280.0,
    coverImage: '/images/no-image.webp',
    images: [],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'auto-005',
    name: 'JLS MIC 15M',
    slug: 'jls-mic-15m',
    description: '',
    price: 360.0,
    coverImage: '/images/no-image.webp',
    images: [],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'auto-006',
    name: 'JLS MIC 20M',
    slug: 'jls-mic-20m',
    description: '',
    price: 420.0,
    coverImage: '/images/no-image.webp',
    images: [],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'auto-007',
    name: 'JLS-HIGH IMP 1.5M',
    slug: 'jls-high-imp-1-5m',
    description: '',
    price: 150.0,
    coverImage: '/images/no-image.webp',
    images: [],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'auto-008',
    name: 'JLS-HIGH IMP 3M',
    slug: 'jls-high-imp-3m',
    description: '',
    price: 170.0,
    coverImage: '/images/no-image.webp',
    images: [],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'auto-009',
    name: 'JLS-HIGH IMP 6M',
    slug: 'jls-high-imp-6m',
    description: '',
    price: 220.0,
    coverImage: '/images/no-image.webp',
    images: [],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'auto-010',
    name: 'JLS-HIGH IMP 10M',
    slug: 'jls-high-imp-10m',
    description: '',
    price: 280.0,
    coverImage: '/images/no-image.webp',
    images: [],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'auto-011',
    name: 'JLS-PATCH 1.5M',
    slug: 'jls-patch-1-5m',
    description: '',
    price: 150.0,
    coverImage: '/images/no-image.webp',
    images: [],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'auto-012',
    name: 'JLS-PATCH 3M',
    slug: 'jls-patch-3m',
    description: '',
    price: 170.0,
    coverImage: '/images/no-image.webp',
    images: [],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'auto-013',
    name: 'JLS-PATCH 6M',
    slug: 'jls-patch-6m',
    description: '',
    price: 220.0,
    coverImage: '/images/no-image.webp',
    images: [],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'auto-014',
    name: 'JLS-PATCH 10M',
    slug: 'jls-patch-10m',
    description: '',
    price: 280.0,
    coverImage: '/images/no-image.webp',
    images: [],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'auto-015',
    name: 'JLS-INST 1.5M',
    slug: 'jls-inst-1-5m',
    description: '',
    price: 150.0,
    coverImage: '/images/no-image.webp',
    images: [],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'auto-016',
    name: 'JLS-INST 3M',
    slug: 'jls-inst-3m',
    description: '',
    price: 170.0,
    coverImage: '/images/no-image.webp',
    images: [],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'auto-017',
    name: 'JLS-INST 6M',
    slug: 'jls-inst-6m',
    description: '',
    price: 220.0,
    coverImage: '/images/no-image.webp',
    images: [],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'auto-018',
    name: 'JLS-INST 10M',
    slug: 'jls-inst-10m',
    description: '',
    price: 280.0,
    coverImage: '/images/no-image.webp',
    images: [],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'auto-019',
    name: 'JLS-DJ*1 1.5M',
    slug: 'jls-dj-1-1-5m',
    description: '',
    price: 125.0,
    coverImage: '/images/no-image.webp',
    images: [],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'auto-020',
    name: 'JLS-DJ*1 3M',
    slug: 'jls-dj-1-3m',
    description: '',
    price: 150.0,
    coverImage: '/images/no-image.webp',
    images: [],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'auto-021',
    name: 'JLS-DJ*2 1.5M',
    slug: 'jls-dj-2-1-5m',
    description: '',
    price: 125.0,
    coverImage: '/images/no-image.webp',
    images: [],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'auto-022',
    name: 'JLS-DJ*2 3M',
    slug: 'jls-dj-2-3m',
    description: '',
    price: 150.0,
    coverImage: '/images/no-image.webp',
    images: [],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'auto-023',
    name: 'JLS-DJ*3 1.5M',
    slug: 'jls-dj-3-1-5m',
    description: '',
    price: 125.0,
    coverImage: '/images/no-image.webp',
    images: [],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'auto-024',
    name: 'JLS-DJ*3 3M',
    slug: 'jls-dj-3-3m',
    description: '',
    price: 150.0,
    coverImage: '/images/no-image.webp',
    images: [],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'auto-025',
    name: 'JLS-DJ*4 1.5M',
    slug: 'jls-dj-4-1-5m',
    description: '',
    price: 170.0,
    coverImage: '/images/no-image.webp',
    images: [],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'auto-026',
    name: 'JLS-DJ*4 3M',
    slug: 'jls-dj-4-3m',
    description: '',
    price: 230.0,
    coverImage: '/images/no-image.webp',
    images: [],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'auto-027',
    name: 'JZG-2X12 100M',
    slug: 'jzg-2x12-100m',
    description: '',
    price: 1200.0,
    coverImage: '/images/no-image.webp',
    images: [],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'auto-028',
    name: 'JZG-2X14 100M',
    slug: 'jzg-2x14-100m',
    description: '',
    price: 800.0,
    coverImage: '/images/no-image.webp',
    images: [],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },
  {
    id: 'auto-029',
    name: 'JZG-2X16 100M',
    slug: 'jzg-2x16-100m',
    description: '',
    price: 670.0,
    coverImage: '/images/no-image.webp',
    images: [],
    categoryId: 'cables-category',
    features: [],
    videoUrl: '',
  },

  // ##############
  // ##############
  // ##############
  // Consola MEZCLA MICROF
  // ##############
  // ##############
  // ##############
  {
    id: 'jzg-409a-mp3',
    name: 'JZG 409A-MP3',
    description: '',
    slug: 'jzg-409a-mp3',
    price: 3200.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-609a-mp3',
    name: 'JZG 609A-MP3',
    description: '',
    slug: 'jzg-609a-mp3',
    price: 3400.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-809-a-mp3',
    name: 'JZG 809 A-MP3',
    description: '',
    slug: 'jzg-809-a-mp3',
    price: 3800.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-424fx',
    name: 'JZG 424FX',
    description: '',
    slug: 'jzg-424fx',
    price: 1820.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-812fx',
    name: 'JZG 812FX',
    description: '',
    slug: 'jzg-812fx',
    price: 4050.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-1216fx',
    name: 'JZG 1216FX',
    description: '',
    slug: 'jzg-1216fx',
    price: 5100.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-1620fx',
    name: 'JZG 1620FX',
    description: '',
    slug: 'jzg-1620fx',
    price: 5920.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg10fx',
    name: 'JZG10FX',
    description: '',
    slug: 'jzg10fx',
    price: 5100.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg14fx',
    name: 'JZG14FX',
    description: '',
    slug: 'jzg14fx',
    price: 6000.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg18fx',
    name: 'JZG18FX',
    description: '',
    slug: 'jzg18fx',
    price: 7000.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-1000afx-mp3',
    name: 'JZG-1000AFX MP3',
    description: '',
    slug: 'jzg-1000afx-mp3',
    price: 6200.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-1600afx-mp3',
    name: 'JZG-1600AFX MP3',
    description: '',
    slug: 'jzg-1600afx-mp3',
    price: 8340.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-16bfx-mp3',
    name: 'JZG-16BFX MP3',
    description: '',
    slug: 'jzg-16bfx-mp3',
    price: 9900.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-24bfx-mp3',
    name: 'JZG-24BFX MP3',
    description: '',
    slug: 'jzg-24bfx-mp3',
    price: 12800.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-32bfx-mp3',
    name: 'JZG-32BFX MP3',
    description: '',
    slug: 'jzg-32bfx-mp3',
    price: 17800.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-pro-x-8.8',
    name: 'JZG-PRO-X 8.8',
    description: '',
    slug: 'jzg-pro-x-8.8',
    price: 9500.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-pro-x-10.8',
    name: 'JZG-PRO-X-10.8',
    description: '',
    slug: 'jzg-pro-x-10.8',
    price: 9800.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'elt-700-pro',
    name: 'ELT 700 PRO',
    description: '',
    slug: 'elt-700-pro',
    price: 400.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-900-pro',
    name: 'JZG 900 PRO',
    description: '',
    slug: 'jzg-900-pro',
    price: 400.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-38-hu-inalambrico',
    name: 'JZG 38 HU INALAMBRICO',
    description: '',
    slug: 'jzg-38-hu-inalambrico',
    price: 3200.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-1000',
    name: 'JZG 1000',
    description: '',
    slug: 'jzg-1000',
    price: 3700.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
  {
    id: 'jzg-1400',
    name: 'JZG 1400',
    description: '',
    slug: 'jzg-1400',
    price: 7100.0,
    coverImage: '',
    images: [],
    categoryId: '',
    features: [],
    videoUrl: '',
  },
];
